const preguntasOperativo = [
    ["Cumple con sus compromisos con desempeño promedio y se establece objetivos dentro de lo esperado.", "Cumple los compromisos con buen desempeño ocasionalmente y se establece objetivos dentro de lo esperado.", "Cumple con frecuencia los compromisos mostrando buen desempeño y tiende a establecerse objetivos por encima de lo esperado.", "Cumple con sus compromisos con alto desempeño frecuentemente y tiende a establecerse objetivos por encima de lo esperado."],
    ["Se fija objetivos personales, rara vez participa en iniciativas técnicas o de mejora con el equipo de trabajo, conoce los aspectos básicos de su trabajo, raramente brinda guía o mentoría a sus compañeros.", "Sigue los objetivos del equipo, ocasionalmente participa con iniciativas técnicas o de mejora en general, conoce los aspectos generales de su trabajo y de otras posiciones, brinda guía o mentoría a sus compañeros ocasionalmente.", "Puede fijar objetivos pensando en lo personal y en el equipo, promueve iniciativas técnicas y de mejora realizando poco seguimiento de lo encomendado. Conoce a profundidad su trabajo. Trabaja con energía y buen ánimo.", "Puede fijar objetivos que son aceptados por el equipo desde el punto de vista técnico y general, realizando un adecuado seguimiento de lo encomendado. Sabe fragmentar tareas. Sus compañeros confían en su expertise, trabaja con energía y buen ánimo."],
    ["Requiere de reforzamiento para mantener organización en sus tareas, puede dejar pasar ocasionalmente algunos errores menores en sus entregables. Requiere monitoreo para apegarse a los procedimientos y normas.", "Organiza sus tareas diarias, mas requiere recordatorio sobre los pendientes. Con frecuencia su trabajo está correcto. Comprende los procedimientos y normas, requiriendo poco monitoreo para el cumplimiento de los mismos.", "Puede fraccionar un problema en partes, aunque tiende a enfocarse en aspectos específicos, tomando poco en cuenta el panorama general de la situación. Su trabajo cumple exactamente con lo requerido, sin mayores aportes o mejoras. Establece prioridades solamente en función a la urgencia. Tiende a organizarse para la ejecución de sus tareas. Se apega a los procedimientos.", "Analiza relaciones de algunas partes de un problema. Casi siempre su trabajo está correcto y con frecuencia da aportes. Establece prioridades para las tareas según su urgencia y en ocasiones la importancia. Es metódico en el abordaje de sus tareas. Se apega a los procedimientos fielmente."],
    ["Prefiere trabajar de forma individual, confía en más en su desempeño personal que en el rendimiento del equipo, rara vez se involucra en acciones grupales, sus logros son individuales.", "Prefiere trabajar de forma individual, aunque se muestra abierto al trabajo en equipo, ocasionalmente se involucra en acciones grupales, sus logros son individuales, con aportes modestos a los logros grupales.", "Le agrada el trabajo en equipo, cumple con las tareas que el grupo le asigna. Apoya los logros compartidos. Privilegia el interés personal, aunque ocasionalmente toma en cuenta los intereses grupales.", "Comprende la necesidad de que todos colaboren para la mejor consecución de los objetivos generales. Se compromete en la búsqueda de logros compartidos. Privilegia el interés del grupo por encima del interés personal."]
];


const preguntasTactico = [];

const preguntasEstrategico = [];


